/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testcreator;

import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Tadeusz
 */
public class CreatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form CreatorWindow
     */
    Test t;
    String pytanie;
    int prawidlowa;
    Enumeration<AbstractButton> en ;
    JRadioButton[] wskazniki;
    JTextField[] odpowiedzi;
    int iter;
    Boolean boo = true;
    private int ilosc;
    private String[] odp;
    /**
     *
     */
    public CreatorWindow() {
        initComponents();
        iter = 0;
        odp = new String[9];
        wskazniki = new JRadioButton[10];
        odpowiedzi = new JTextField[9];
        t = new Test();     
        int ilosc;
        en = buttonGroup1.getElements();
        int i = 0;
        while (en.hasMoreElements())
        {
            en.nextElement().setText("" + ++i + ".");
        }
        buttonGroup1.add(jRadioButton11);
        en = buttonGroup1.getElements();
        i = 0;
        while (en.hasMoreElements())
        {
            wskazniki[i++] = (JRadioButton)en.nextElement();
        }
        odpowiedzi[0] = jTextField1; 
        odpowiedzi[1] = jTextField2;
        odpowiedzi[2] = jTextField4;
        odpowiedzi[3] = jTextField5;
        odpowiedzi[4] = jTextField6;
        odpowiedzi[5] = jTextField7;
        odpowiedzi[6] = jTextField8;
        odpowiedzi[7] = jTextField9;
        odpowiedzi[8] = jTextField10;
        prevButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unSelected")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        questionTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jTextField7 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jTextField10 = new javax.swing.JTextField();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        jRadioButton11.setText("jRadioButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pytanie: ");

        questionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionTextFieldActionPerformed(evt);
            }
        });
        questionTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                questionTextFieldFocusLost(evt);
            }
        });
        questionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                questionTextFieldKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1");
        jRadioButton1.setEnabled(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1InputMethodTextChanged(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("1");
        jRadioButton2.setEnabled(false);
        jRadioButton2.setFocusable(false);
        jRadioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addGap(31, 31, 31)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("1");
        jRadioButton4.setEnabled(false);
        jRadioButton4.setFocusable(false);
        jRadioButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton4)
                .addGap(31, 31, 31)
                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("1");
        jRadioButton5.setEnabled(false);
        jRadioButton5.setFocusable(false);
        jRadioButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton5)
                .addGap(31, 31, 31)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("1");
        jRadioButton6.setEnabled(false);
        jRadioButton6.setFocusable(false);
        jRadioButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton6)
                .addGap(31, 31, 31)
                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("1");
        jRadioButton7.setEnabled(false);
        jRadioButton7.setFocusable(false);
        jRadioButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField7.setEnabled(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton7)
                .addGap(31, 31, 31)
                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("1");
        jRadioButton8.setEnabled(false);
        jRadioButton8.setFocusable(false);
        jRadioButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField8.setEnabled(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton8)
                .addGap(31, 31, 31)
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("1");
        jRadioButton9.setEnabled(false);
        jRadioButton9.setFocusable(false);
        jRadioButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton9)
                .addGap(31, 31, 31)
                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("1");
        jRadioButton10.setEnabled(false);
        jRadioButton10.setFocusable(false);
        jRadioButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextField10.setEnabled(false);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton10)
                .addGap(31, 31, 31)
                .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        prevButton.setText("Poprzednie");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Następne");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(prevButton)
                        .addGap(123, 123, 123)
                        .addComponent(nextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(questionTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel10, jPanel2, jPanel4, jPanel5, jPanel6, jPanel7, jPanel8, jPanel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevButton)
                    .addComponent(nextButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel10, jPanel2, jPanel4, jPanel5, jPanel6, jPanel7, jPanel8, jPanel9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed

        if(sprawdzElementy()!=0)
    {
          JOptionPane.showMessageDialog(this,"Popraw dane.","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }
    pytanie = questionTextField.getText();
    for (int i = 0; i < 9; ++i)
    {
        if (wskazniki[i].isSelected())
            prawidlowa = i;
    }
    ilosc = 9;
    for (int i = 0; i < 9; ++i)
    {
        if(!"".equals(odpowiedzi[i].getText()))
            odp[i] = odpowiedzi[i].getText();
        else
        {
            ilosc = i;
            break;
        }
    }
    if (ilosc == 0)
    {
        --iter;
        loadQuestion(iter);
        return;
    }
    int i;
    for (i = 0; i < 9; ++i)
    {
        if(wskazniki[i].isSelected())
        {
            prawidlowa = i;
            break;
        }
    }
    if (i == 9)
    {
          JOptionPane.showMessageDialog(this,"Zaznacz prawidłową odpowiedź","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if(sprawdzElementy()!=0)
    {
          JOptionPane.showMessageDialog(this,"Popraw dane.","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }
    Question q = new Question();
    q.setQuest(pytanie);
    q.right_ans=prawidlowa;
    q.count=ilosc;
    for (int j = 0; j < ilosc; ++j)
        q.ans[j]=odp[j];
    if (iter >= t.test.size())
        t.test.addElement(q);
    else
        t.test.setElementAt(q, iter);
    --iter;
    loadQuestion(iter);
    if (iter  == 0)
    {
        prevButton.setEnabled(false);
    }
    if (t.test.elementAt(iter).right_ans > -1)
    {
      wskazniki[t.test.elementAt(iter).right_ans].setSelected(true);
    }

    }//GEN-LAST:event_prevButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
            if ("".equals(odpowiedzi[2].getText()) && "".equals(odpowiedzi[1].getText()))
            {
                odpowiedzi[2].setEnabled(false);
                wskazniki[1].setEnabled(false);
            }
            else
            {
                odpowiedzi[2].setEnabled(true);
                wskazniki[1].setEnabled(true);
            }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void questionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionTextFieldActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
    if("".equals(questionTextField.getText()))
    {
     JOptionPane.showMessageDialog(this,"Nie podałeś pytania","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if(sprawdzElementy()!=0)
    {
          JOptionPane.showMessageDialog(this,"Popraw dane.","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }
    int i;
    for (i = 0; i < 9; ++i)
    {
        if(wskazniki[i].isSelected())
        {
            prawidlowa = i;
            break;
        }
    }
    if (i == 9)
    {
          JOptionPane.showMessageDialog(this,"Zaznacz prawidłową odpowiedź","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if(sprawdzElementy()!=0)
    {
          JOptionPane.showMessageDialog(this,"Popraw dane.","Uwaga", JOptionPane.WARNING_MESSAGE);
        return;
    }
    prevButton.setEnabled(true);
    pytanie = questionTextField.getText();
    ilosc = 9;
    for (int j = 0; j < 9; ++j)
    {
        if(!"".equals(odpowiedzi[j].getText()))
        {
            odp[j] = odpowiedzi[j].getText();
        }
        else
        {
            ilosc = j;
            break;
        }
    }

    Question q = new Question();
    q.setQuest(pytanie);
    q.right_ans=prawidlowa;
    q.count=ilosc;
    for (int j = 0; j < ilosc; ++j)
        q.ans[j]=odp[j];
    if (iter >= t.test.size())
        t.test.addElement(q);
    else
        t.test.setElementAt(q, iter);
    if(iter == t.test.size()-1)
    {

            nowePytanie();
            odpowiedzi[0].setText("");
            odpowiedzi[1].setText("");
            odpowiedzi[2].setText("");
            odpowiedzi[3].setText("");
            odpowiedzi[4].setText("");
            odpowiedzi[5].setText("");
            odpowiedzi[6].setText("");
            odpowiedzi[7].setText("");
            odpowiedzi[8].setText("");

            questionTextField.setText("");
            ++iter;
            saveButton.setEnabled(true);
    }
    else
    {
        loadQuestion(++iter);
        if (t.test.elementAt(iter).right_ans > -1)
        {
          wskazniki[t.test.elementAt(iter).right_ans].setSelected(true);
          saveButton.setEnabled(true);
        }
    }

    }//GEN-LAST:event_nextButtonActionPerformed

    private void questionTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_questionTextFieldFocusLost
            
    }//GEN-LAST:event_questionTextFieldFocusLost

    private void jTextField1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1InputMethodTextChanged

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost

    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
            if ("".equals(odpowiedzi[2].getText()) && "".equals(odpowiedzi[1].getText()))
            {
                odpowiedzi[2].setEnabled(false);
                wskazniki[1].setEnabled(false);
            }
            else
            {
                odpowiedzi[2].setEnabled(true);
                wskazniki[1].setEnabled(true);
            }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
 
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
            if ("".equals(odpowiedzi[2].getText()) && "".equals(odpowiedzi[3].getText()))
            {
                odpowiedzi[3].setEnabled(false);
                wskazniki[2].setEnabled(false);
            }
            else
            {
                odpowiedzi[3].setEnabled(true);
                wskazniki[2].setEnabled(true);
            }
           
    }//GEN-LAST:event_jTextField4KeyReleased

    private void questionTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_questionTextFieldKeyReleased
           if ("".equals(questionTextField.getText()) && "".equals(odpowiedzi[0].getText()))
            {
                odpowiedzi[0].setEnabled(false);           
            }
            else
            {
                odpowiedzi[0].setEnabled(true);
            }
    
    }//GEN-LAST:event_questionTextFieldKeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
           if ("".equals(odpowiedzi[1].getText()) && "".equals(odpowiedzi[2].getText())&&"".equals(odpowiedzi[3].getText()) && "".equals(odpowiedzi[4].getText())&& "".equals(odpowiedzi[5].getText())&&"".equals(odpowiedzi[6].getText()) && "".equals(odpowiedzi[7].getText())&& "".equals(odpowiedzi[8].getText()))
            {
                odpowiedzi[2].setEnabled(false);
                wskazniki[1].setEnabled(false);
            }
            else
            {
                odpowiedzi[2].setEnabled(true);
                wskazniki[1].setEnabled(true);
            }
               }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        if ("".equals(odpowiedzi[1].getText()) && "".equals(odpowiedzi[0].getText())&& "".equals(odpowiedzi[2].getText())&&"".equals(odpowiedzi[3].getText()) && "".equals(odpowiedzi[4].getText())&& "".equals(odpowiedzi[5].getText())&&"".equals(odpowiedzi[6].getText()) && "".equals(odpowiedzi[7].getText())&& "".equals(odpowiedzi[8].getText()))
            {
                odpowiedzi[1].setEnabled(false);
                wskazniki[0].setEnabled(false);
            }
            else
            {
                odpowiedzi[1].setEnabled(true);
                wskazniki[0].setEnabled(true);
               
            }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        if ("".equals(odpowiedzi[3].getText()) && "".equals(odpowiedzi[4].getText())&& "".equals(odpowiedzi[5].getText())&&"".equals(odpowiedzi[6].getText()) && "".equals(odpowiedzi[7].getText())&& "".equals(odpowiedzi[8].getText()))
            {
                odpowiedzi[4].setEnabled(false);
                wskazniki[3].setEnabled(false);
            }
            else
            {
                odpowiedzi[4].setEnabled(true);
                wskazniki[3].setEnabled(true);
               
            }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
if ("".equals(odpowiedzi[4].getText()) && "".equals(odpowiedzi[5].getText())&&"".equals(odpowiedzi[6].getText()) && "".equals(odpowiedzi[7].getText())&& "".equals(odpowiedzi[8].getText()))
            {
                odpowiedzi[5].setEnabled(false);
                wskazniki[4].setEnabled(false);
            }
            else
            {
                odpowiedzi[5].setEnabled(true);
                wskazniki[4].setEnabled(true);
               
            }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        if ("".equals(odpowiedzi[5].getText()) && "".equals(odpowiedzi[6].getText())&&"".equals(odpowiedzi[7].getText()) && "".equals(odpowiedzi[8].getText()))
            {
                odpowiedzi[6].setEnabled(false);
                wskazniki[5].setEnabled(false);
            }
            else
            {
                odpowiedzi[6].setEnabled(true);
                wskazniki[5].setEnabled(true);
               
            }
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        if ("".equals(odpowiedzi[6].getText()) && "".equals(odpowiedzi[7].getText())&& "".equals(odpowiedzi[8].getText()))
            {
                odpowiedzi[7].setEnabled(false);
                wskazniki[6].setEnabled(false);
            }
            else
            {
                odpowiedzi[7].setEnabled(true);
                wskazniki[6].setEnabled(true);
               
            }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
if ("".equals(odpowiedzi[8].getText()) && "".equals(odpowiedzi[7].getText()))
            {
                odpowiedzi[8].setEnabled(false);
                wskazniki[7].setEnabled(false);
            }
            else
            {
                odpowiedzi[8].setEnabled(true);
                wskazniki[7].setEnabled(true);
               
            }        // TODO add your handling code here:^
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
if ("".equals(odpowiedzi[8].getText()))
            {
                wskazniki[8].setEnabled(false);
            }
            else
            {
                wskazniki[8].setEnabled(true);  
            }
    }//GEN-LAST:event_jTextField10KeyReleased

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        t.skala[0] = 1.1;//2 // 2 jako dop.
        t.skala[1] = 1.1;//2+
        t.skala[2] = 0.5;//3
        t.skala[3] = 0.6;//3+
        t.skala[4] = 0.7;//4
        t.skala[5] = 0.8;//4+
        t.skala[6] = 0.9;//5
        t.skala[7] = 1.1;//5+
        t.skala[8] = 7.0;//6
        ScaleDialog sc = new ScaleDialog(this,true,t.skala);
        sc.setVisible(true);
        if (t.skala[8]==7.0) return;
        JFileChooser fc = new JFileChooser();
        
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Simple test file", "stf"));
        fc.setAcceptAllFileFilterUsed(false);
        int r;
        r = fc.showSaveDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        if (!file.getName().endsWith(".stf"))
        {
            file = new File(fc.getSelectedFile().getName() + ".stf");
        }
        {	
            try (ObjectOutputStream i = new ObjectOutputStream(
                           new FileOutputStream(file))) {
                try
                {        
                       i.writeObject(t);
                       t = new Test();
                }
                catch (Exception e)
                {
                    
                }
            } catch (IOException ex) {}
        }
    }
   
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CreatorWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JTextField questionTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
void clear(){
        wskazniki[9].setSelected(true);
}
int sprawdzElementy(){
    for (int i = 0; i < 9; ++i)
    {
        if(wskazniki[i].isSelected()&&"".equals(odpowiedzi[i].getText()))
            return 1;
    }
    boolean exists = false;
    for (int i = 1; i < 9; ++i)
    {
        if("".equals(odpowiedzi[i-1].getText()))
            exists = true;
        if (!"".equals(odpowiedzi[i].getText())&& exists)
            return 2;
    }
return 0;
}
void loadQuestion(int n)
{
    clear();
    if (n < 0)
    {
        questionTextField.setText(""+n);
        return;
    }

    if(n > t.test.size()) return;
    questionTextField.setText(t.test.elementAt(n).getQuest());
    for (int i = 0; i < 9; ++i)
    {
        if(i < t.test.elementAt(n).getCount())
        {
            String qs = t.test.elementAt(n).getAns(i);
            odpowiedzi[i].setText(qs);
            wskazniki[i].setEnabled(true);
            odpowiedzi[i].setEnabled(true);
        }
        else if(i == t.test.elementAt(n).getCount())
        {
            odpowiedzi[i].setText("");
            odpowiedzi[i].setEnabled(true);
            wskazniki[i].setEnabled(false);
        }
            else
            {
                odpowiedzi[i].setText("");
                odpowiedzi[i].setEnabled(false);
                wskazniki[i].setEnabled(false);
            }
    }

    if (t.test.elementAt(n).right_ans < 0)
    {
        clear();
    }

    if (t.test.elementAt(n).right_ans > -1)
    {
      wskazniki[t.test.elementAt(n).right_ans].setSelected(true);
    }


    nextButton.setEnabled(true);
    prevButton.setEnabled(true);

    if (n >= t.test.size() -1)
    {
        //nextButton.setText("Dodaj");
        prevButton.setEnabled(true);
    }
    else
    {
        //nextButton.setText("Następne");
        prevButton.setEnabled(true);
    }
    if (n  == 0)
    {
        prevButton.setEnabled(false);
    }
}
void nowePytanie()
{
    clear();

    for (int i = 0; i <9; ++i )
    {
        odpowiedzi[i].setText("");
        odpowiedzi[i].setEnabled(false);
        wskazniki[i].setEnabled(false);
    }
}
}